[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = [
  "rm -rf node_modules",
  "pnpm store prune",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "cd packages/database && pnpm prisma generate",
  "cd apps/backend && pnpm build"
]

[start]
cmd = "cd apps/backend && node dist/main.js"
